name: diffdock
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torch-geometric
    - e3nn
    - rdkit
    - prody
    - pytorch-lightning
    - pandas
    - scikit-learn
    - fair-esm
